properties/P000099.md

Make sequentially Hausdorff an alias for US property

---

spaces/S000010/properties/P000034.md
spaces/S000015/properties/P000099.md
spaces/S000016/properties/P000099.md
spaces/S000017/properties/P000103.md
spaces/S000036/properties/P000103.md

US and KC related properties for cofinite and cocountable topologies.
Plus one cleanup.

KC related

---

README.md
properties/P000023.md
properties/P000024.md
properties/P000130.md
spaces/S000029/properties/P000130.md
theorems/T000245.md
theorems/T000246.md

address strong/weak local compactness as discussed in #42

---

properties/P000023.md
properties/P000130.md

To keep a consistent voice between locally compact, weakly locally compact, and locally relatively compact, the descriptive language has been changed. Namely, the language "A space X is said to be P if every point of X...." has been changed to "Each point has Q".

Consistent voice local compact

---

properties/P000129.md
theorems/T000083.md

Minor rewording for "trivial topology"

---

spaces/S000016/properties/P000129.md
theorems/T000253.md

This will allow to deduce indiscrete=false for many spaces and remove many P000129.md files.
Also removing P000129.md for S16 (cofinite topology on the reals) as proof of concept.

Add theorem: distinct points + T0 implies not indiscrete

---

theorems/T000258.md
theorems/T000259.md
theorems/T000260.md
theorems/T000261.md

Adding a few simple theorems to increase the coverage of these properties.
- T259: countable implies hereditarily Lindelof
- T260: second countable implies hereditarily Lindelof
- T261: countable + T1 implies G_delta space

Some theorems about hereditarily Lindelof and G_delta spaces

---

properties/P000059.md

Hotfix for incorrect P59 title

---

spaces/S000065/properties/P000037.md
spaces/S000065/properties/P000038.md

This fixes an error from Steen & Seebach.

Telophase topology is path connected, not arc connected

---

spaces/S000107/properties/P000006.md
spaces/S000107/properties/P000008.md
spaces/S001103/properties/P000006.md

Follow-up to the discussion in issue https://github.com/pi-base/data/issues/117.
N.b. that the citation style used in the "name" field of property P000008 might need revision.
Also fixed a minor grammar mistake I spotted in another space.
@StevenClontz, @prabau, @jamesdabbs

Corrected the asserted properties of space S000107

---

theorems/T000268.md

This handles half of issue #90.
Optionally, if you want to, we could add a reference to J. Kelley, General Topology, as it is stated explicitly in Exercise K, p. 134 in that book ("Each pseudometrizable space is perfectly normal").  You'd have to get the MR number for it (I don't have access to MR).
@StevenClontz

New theorem: Pseudometrizable spaces are perfectly normal

---

spaces/S000171/README.md
spaces/S000171/properties/P000003.md
spaces/S000171/properties/P000018.md
spaces/S000171/properties/P000028.md
spaces/S000171/properties/P000051.md
spaces/S000171/properties/P000057.md
spaces/S000171/properties/P000065.md

add brian's example

---

properties/P000029.md
theorems/T000276.md
theorems/T000277.md

Adding two theorems:
276: hereditary Lindelof ==> CCC
277: LOTS + CCC ==> hereditary Lindelof
(streamlined definition of CCC per #83)

Two new theorems involving hereditarily Lindelof

---

properties/P000134.md
theorems/T000281.md
theorems/T000282.md
theorems/T000283.md

With theorems:
- (T281) T2 --> preregular
- (T282) regular --> preregular
- (T283) preregular + T0 --> T2
Will be used with issue #157

Add preregular property

---

spaces/S000005/properties/P000090.md
spaces/S000006/properties/P000090.md
spaces/S000008/properties/P000090.md
spaces/S000009/properties/P000090.md
spaces/S000012/properties/P000090.md
spaces/S000013/properties/P000090.md
spaces/S000014/properties/P000090.md

Asserting the Alexandrov property (P90) for some spaces:
- S5 (odd-even topology)
- S6 (deleted integer topology)
- S8 (particular point topology on a countably infinite set)
- S9 (particular point topology on the real numbers)
- S12 (excluded point topology on a countably infinite set)
- S13 (excluded point topology on the real numbers)
- S14 (either-or topology)

Some spaces with the Alexandrov property

---

theorems/T000290.md

Fix typo in T290

---

properties/P000136.md
theorems/T000292.md
theorems/T000293.md
theorems/T000294.md

Add theorems on compact-sets-are-finite spaces

---

theorems/T000300.md

Fix typo in T300

---

theorems/T000301.md

As discussed in #189 and #188.

New theorem: countably many self-maps + Alexandrov imply finite

---

theorems/T000049.md

- (old T49) Totally disconnected ==> T1
- (new T49) Totally path disconnected ==> T1

T49 generalization

---

theorems/T000303.md
theorems/T000304.md
theorems/T000305.md

- (T303) Anticompact + compact ==> finite
- (T304) Anticompact + sigma-compact ==> countable
- (T305) Anticompact + T1 ==> totally path disconnected
By contraposition, these theorems allow to automatically deduce that many extra spaces are not anticompact.

Some theorems about anticompact

---

spaces/S000047/README.md

As discussed in #187.
Will add the anticompact property and do some cleanup separately.

Hjalmar Ekdal: change principal name

---

spaces/S000063/README.md

Add Michael Line

---

spaces/S000063/README.md

More references involving the Michael line.
Also removed the word "rational" from the description.

Michael line update

---

properties/P000064.md
theorems/T000317.md

New theorem: scattered implies Baire

---

theorems/T000275.md

fix: add ref name to mathse ref

---

properties/P000143.md
theorems/T000227.md
theorems/T000229.md

Introducing weak Hausdorff (P143) as it is tied to some of the "compactly generated" variants and will be needed in related theorems.
Weak Hausdorff is clearly between T2 and T1.  And it is implied by KC (P100)  Does it imply US (P99) maybe?

Weak Hausdorff property

---

theorems/T000330.md
theorems/T000331.md

Rounding out the theorems about locally pseudometrizable:
- T330: locally pseudometrizable ==> R0
- T331: locally pseudometrizable + T0 ==> locally metrizable

More theorems about locally pseudometrizable

---

theorems/T000332.md

This gives us a list of spaces which are locally metrizable but not locally Euclidean.

Add "Locally Euclidean -> Locally Compact"

---

theorems/T000208.md

This adds the automated deduction of https://topology.pi-base.org/spaces/S000004/properties/P000139 (indiscrete space with two points has no isolated point).
This resolves issue #204.

T208: indiscrete + distinct points ==> no isolated point

---

spaces/S000156/properties/P000079.md

Gives counterexample to converse of https://topology.pi-base.org/theorems/T000184

add sequential property to arens space

---

properties/P000043.md
theorems/T000082.md

@ccaruvana Another one related to locally Euclidean.
Will deduce locally arc connected for S153 and S170:
https://topology.pi-base.org/spaces?q=Locally%20Euclidean%2BLocally%20Arc%20Connected

T82: locally euclidean => locally arc connected

---

spaces/S000063/properties/P000008.md
spaces/S000063/properties/P000015.md
spaces/S000063/properties/P000030.md
spaces/S000077/README.md
spaces/S000077/properties/P000005.md
spaces/S000077/properties/P000006.md

Add T3 (and therefore T0) to S77.

improve regular to t3

---

theorems/T000023.md
theorems/T000029.md

remove T0 assumption in T23

---

properties/P000034.md

Fix for Fully normal (P34)

---

spaces/S000174/README.md
spaces/S000174/properties/P000030.md
spaces/S000174/properties/P000067.md
spaces/S000174/properties/P000082.md
spaces/S000174/properties/P000088.md

Asked at https://math.stackexchange.com/questions/4675267/ until I thought to search for paracompact instead of fully normal.

Add a perfectly normal, non fully normal space

---

spaces/S000165/properties/P000141.md
spaces/S000165/properties/P000143.md
theorems/T000059.md
theorems/T000060.md
theorems/T000069.md
theorems/T000070.md

Generalized theorem T59, plus new theorems T60 and T69, related to various notions of compactly generated space.
See #230.

Some theorems involving compactly generated

---

spaces/S000135/README.md
spaces/S000175/README.md
spaces/S000175/properties/P000003.md
spaces/S000175/properties/P000011.md
spaces/S000175/properties/P000018.md
spaces/S000175/properties/P000025.md
spaces/S000175/properties/P000026.md
spaces/S000175/properties/P000065.md
spaces/S000175/properties/P000079.md
spaces/S000175/properties/P000080.md

Closes #111 but we need to add MR numbers (or other bib info) for a couple references. (I'm off campus today.)

add radial plane

---

theorems/T000225.md
theorems/T000267.md

Add theorem: [first countable + P-space ==> Alexandrov].  This allows to deduce that many more spaces are not P-spaces.
Also added converse to T267.

T225: first countable + P-space ==> Alexandrov

---

theorems/T000114.md

fixes proof to use T1 instead of T0

---

spaces/S000180/README.md
spaces/S000180/properties/P000006.md
spaces/S000180/properties/P000050.md
spaces/S000180/properties/P000051.md

add P51 not P50 space

---

properties/P000039.md
properties/P000049.md
theorems/T000045.md
theorems/T000096.md
theorems/T000097.md

Remove T2 assumption from P49.
As discussed in https://github.com/pi-base/data/pull/357#issuecomment-1646738969.

Extremally disconnected: remove T2 assumption

---

.vscode/settings.json
spaces/S000110/properties/P000059.md
spaces/S000110/properties/P000147.md
spaces/S000110/properties/P000163.md

Strong ultrafilter topology is not a P-space + cardinality of it. [local branch]

---

properties/P000009.md

closes https://github.com/pi-base/data/issues/382

less ambiguous name for P9

---

spaces/S000090/README.md

Fix old brubeck link

---

spaces/S000182/README.md
spaces/S000182/properties/P000029.md
spaces/S000182/properties/P000050.md
spaces/S000182/properties/P000053.md
spaces/S000182/properties/P000055.md
spaces/S000182/properties/P000056.md
spaces/S000182/properties/P000065.md
spaces/S000182/properties/P000086.md
spaces/S000182/properties/P000093.md

Minor fixes to https://github.com/pi-base/data/pull/393

Minor attempts to fix compile error

---

properties/P000019.md
properties/P000021.md
spaces/S000110/properties/P000021.md
spaces/S000110/properties/P000129.md
spaces/S000110/properties/P000147.md

In particular, a simpler argument for https://topology.pi-base.org/spaces/S000110/properties/P000147.
@Moniker1998 fyi

S110 minor cleanup

---

properties/P000024.md
spaces/S000083/README.md
spaces/S000083/properties/P000002.md
spaces/S000083/properties/P000022.md
spaces/S000083/properties/P000024.md
spaces/S000083/properties/P000027.md
spaces/S000083/properties/P000030.md
spaces/S000083/properties/P000037.md
spaces/S000083/properties/P000038.md
spaces/S000083/properties/P000065.md
spaces/S000083/properties/P000086.md
spaces/S000083/properties/P000099.md
spaces/S000083/properties/P000123.md

New space: line with two origins.

S83: line with two origins

---

properties/P000116.md
theorems/T000199.md
theorems/T000200.md
theorems/T000201.md

Polish property (P116)

---

spaces/S000066/properties/P000003.md

Fix issues pointed out in #441

---

properties/P000114.md
spaces/S000035/properties/P000114.md
spaces/S000036/properties/P000114.md
spaces/S000036/properties/P000163.md
spaces/S000037/properties/P000114.md
spaces/S000078/properties/P000114.md
spaces/S000079/properties/P000114.md
spaces/S000087/properties/P000114.md
spaces/S000088/properties/P000114.md
spaces/S000089/properties/P000114.md
spaces/S000090/properties/P000114.md
spaces/S000177/properties/P000114.md
spaces/S000178/properties/P000114.md
theorems/T000190.md
theorems/T000191.md

New property P114: cardinality = $\aleph_1$ and two theorems relating it to other cardinality properties.
Asserting it for various spaces and clean up of deducible traits: P57 (countable) = false, P163 (card $\le\mathfrak c$) = true.

New property: cardinality aleph_1

---

properties/P000044.md

Add connected to biconnected definition.

---

properties/P000125.md

Suggested revision for P125 to make clear that we don't mean "topologically distinct".

Change "distinct" to "multiple"

---

spaces/S001103/properties/P000029.md

add ccc to S1103

---

spaces/S000079/properties/P000032.md
spaces/S000079/properties/P000033.md
spaces/S000088/README.md
spaces/S000088/properties/P000005.md
spaces/S000088/properties/P000009.md
spaces/S000088/properties/P000031.md
spaces/S000088/properties/P000032.md
spaces/S000088/properties/P000047.md
spaces/S000088/properties/P000051.md
spaces/S000088/properties/P000129.md
spaces/S000089/properties/P000031.md
spaces/S000089/properties/P000032.md
spaces/S000089/properties/P000129.md

Tychonoff corkscrew (S88): add missing traits from Counterexamples

Tychonoff corkscrew: add missing traits

---

spaces/S000022/properties/P000147.md

As in the title.  Among other things, this will imply that the space is sequentially discrete.

Fortissimo space is a P-space

---

properties/P000099.md

See https://doi.org/10.4153/CMB-1966-045-1

add P99 alias

---

.github/workflows/compile.yml

as well as S3. This gives us room to incrementally move over to R2 if and as desired.

ci: upload data to R2

---

spaces/S000165/properties/P000084.md
theorems/T000435.md
theorems/T000436.md

add P84 to S165, add T435, add T436 (#525)

---

spaces/S000131/README.md
spaces/S000131/properties/P000023.md
spaces/S000131/properties/P000050.md
spaces/S000131/properties/P000057.md
spaces/S000131/properties/P000080.md
spaces/S000131/properties/P000111.md
spaces/S000131/properties/P000126.md

Adding the Sequential fan with countably many spines.
This provides an example for
https://topology.pi-base.org/spaces?q=hemicompact%2BFr%C3%A9chet+Urysohn%2B%7EWeakly+Locally+Compact

S131: sequential fan

---

theorems/T000010.md

Update T10 about extremally disconnected

---

spaces/S000139/README.md
spaces/S000139/properties/P000023.md
spaces/S000139/properties/P000026.md
spaces/S000139/properties/P000038.md
spaces/S000139/properties/P000043.md
spaces/S000139/properties/P000064.md
spaces/S000139/properties/P000067.md
spaces/S000139/properties/P000080.md
spaces/S000139/properties/P000086.md
spaces/S000139/properties/P000111.md

This provides an additional example for
https://topology.pi-base.org/spaces?q=hemicompact%2BFr%C3%A9chet+Urysohn%2B%7EWeakly+Locally+Compact

S139: Countable bouquet of circles

---

spaces/S000024/README.md

fix S24 description to be accurate

---

theorems/T000442.md

add sufficient conditions for metacompact

---

properties/P000057.md
properties/P000058.md
properties/P000059.md
properties/P000065.md
properties/P000078.md
properties/P000114.md
properties/P000137.md
properties/P000181.md
theorems/T000454.md
theorems/T000455.md
theorems/T000456.md

audit cardinality properties

---

properties/P000182.md
theorems/T000093.md
theorems/T000259.md
theorems/T000260.md
theorems/T000271.md
theorems/T000334.md

Add property P182 (Has a countable network), as discussed in #511.
Added theorems that relate it to others properties as indicated in the diagram on p. 225 of Engelking.  Plus T334 [countable network + T0 ==> $|X|\le\mathfrak c$].
More theorems and trait adjustments in a later PR.

P182: Has a countable network

---

properties/P000061.md
properties/P000062.md
properties/P000063.md
properties/P000067.md
properties/P000069.md
properties/P000070.md

Adjust descriptions for P61-P70

---

properties/P000073.md
properties/P000081.md
properties/P000082.md
properties/P000089.md
properties/P000090.md

Adjust descriptions for P71-P90

---

properties/P000103.md
properties/P000128.md
properties/P000129.md
properties/P000131.md
properties/P000149.md
properties/P000150.md
properties/P000153.md
properties/P000156.md
properties/P000159.md

Last batch.  This completes issue #83.

Adjust descriptions for P91-P181

---

theorems/T000062.md

generalize T62

---

theorems/T000178.md
theorems/T000179.md
theorems/T000457.md
theorems/T000458.md

Answers https://topology.pi-base.org/spaces/?q=%7ECompact%2BCorson+compact

corson compact is compact

---

properties/P000184.md
theorems/T000459.md
theorems/T000460.md
theorems/T000461.md
theorems/T000462.md
theorems/T000463.md

Add property "Embeddable into Euclidean space"

---

spaces/S000121/README.md

minor s121 readme tweaks

---

spaces/S000005/properties/P000087.md
spaces/S000025/properties/P000087.md
spaces/S000028/properties/P000087.md
spaces/S000054/properties/P000087.md
spaces/S000101/properties/P000087.md
spaces/S001103/properties/P000087.md

Fixing some traits for topological groups (P87) due to some stale references.

Misc fixes for topological groups

---

spaces/S000099/properties/P000003.md
spaces/S000099/properties/P000014.md
spaces/S000099/properties/P000129.md

add note of S&S first edition error

---

properties/P000188.md
theorems/T000480.md
theorems/T000481.md
theorems/T000482.md
theorems/T000483.md

add continuum and theorems

---

theorems/T000131.md

Edited T131 according to #660 .

Edit to T131

---

theorems/T000488.md

Update T488 as mentioned in #663 . Please kindly check my wording :)

Update T488 for GO-spaces

---

theorems/T000507.md

Update T507 [ $k_{\omega,3}$ ==> T2] to have a T4 conclusion.
This allows to deduce two more spaces are not $k_{\omega,3}$.

T507 update

---

spaces/S000171/properties/P000166.md

Changed "Hausdorff" property to "Has a coarser separable metrizable topology".

Brian's space refines the Euclidean real numbers.

---

spaces/S000018/README.md
spaces/S000018/properties/P000135.md

I randomly wondered if there was any space in Pi-Base that is $R_0$ but it isn't $T_0$ nor normal simultaneously.
I noticed after that this space was the only one in the base that had $R_0$ pending to be determined.

S18 is P135.

---

spaces/S000043/properties/P000076.md

Adds result for https://topology.pi-base.org/spaces?q=W-space%2B%7EProximal

add fact that sorgenfrey line is not proximal

---

spaces/S000014/properties/P000126.md

@prabau was right in #722 - I made the argument overly convoluted.

Cleaner S14/P126 argument

---

theorems/T000518.md

Note: change last "first countable" to {P28}.

Well-based + Countable pseudocharacter ==> First countable.

---

theorems/T000524.md

Add ~empty+completely metrizable+~has an isolated point => ~cardinality < c

---

theorems/T000522.md

Per issue #727 and the request under the already closed PR #729 .

Add LOTS+connected=>locally connected

---

theorems/T000523.md
theorems/T000526.md

Per issue #727 and PR #729 .
@prabau said that this {T523} needed discussion after the approval of {T522} :)

Add LOTS+path-connected=>locally path-connected

---

theorems/T000525.md

Among other things, answers https://topology.pi-base.org/spaces?q=compact+%2B+%24T_2%24+%2B+W-space+%2B+%7ECorson+compact

Add theorem that separable Corson compacta are metrizable

---

theorems/T000109.md

This strengthens [T109](https://topology.pi-base.org/theorems/T000109) to use $R_0$ and Indiscrete rather than $T_1$ and Has multiple points.

Strengthen T109

---

properties/P000135.md
theorems/T000487.md

Like my last PR, here's another theorem strengthened by using $R_0$ and Indiscrete rather than $T_1$ and Has multiple points.

Strengthen T487

---

spaces/S000195/properties/P000051.md

[S195](https://topology.pi-base.org/spaces/S000195) Join of cofinite and left-ray topologies on $\omega_1$ is [P51](https://topology.pi-base.org/properties/P000051) Scattered.

S195 is scattered

---

spaces/S000140/properties/P000191.md

I wanted to find an example of a space verifying the following: [Hereditarily Lindelöf+Hereditarily separable+T_1+~Has points $G_\delta$](https://topology.pi-base.org/spaces?q=Hereditarily+Lindel%C3%B6f%2BHereditarily+separable%2BT_1%2B%7EHas+points+%24G_%5Cdelta%24).
[Real numbers extended by a point with co-countable open neighborhoods](https://topology.pi-base.org/spaces/S000140) was a candidate to study. See [Hereditarily Lindelöf+Hereditarily separable+T_1+~Has points $G_\delta$](https://topology.pi-base.org/spaces?q=Hereditarily+Lindel%C3%B6f%2BHereditarily+separable%2BT_1%2B%3FHas+points+%24G_%5Cdelta%24).

S140 doesn't have countable pseudocharacter.

---

spaces/S000016/properties/P000126.md
spaces/S000016/properties/P000182.md
spaces/S000016/properties/P000183.md
spaces/S000016/properties/P000189.md

- Has a countable network (P182): T.
- $\sigma$-connected (P189): T.
- Door (P126): F.
Provides an example of a space verifying: [Has a countable network+T_1+~Has points $G_\delta$](https://topology.pi-base.org/spaces?q=Has+a+countable+network%2BT_1%2B%7EHas+points+%24G_%5Cdelta%24).
My bad, the previous PR got closed because I have changed the name to the branch.

R with the cofinite topology update.

---

theorems/T000538.md

I admit that this look a bit artificial, especially that this theorem does not add to the proof that some spaces have some properties. Any points of view?

Add GO-space + sequentially discrete => anticompact

---

spaces/S000015/properties/P000086.md
spaces/S000017/properties/P000086.md
spaces/S000018/properties/P000086.md
spaces/S000019/properties/P000086.md
spaces/S000038/properties/P000086.md
spaces/S000039/properties/P000086.md
spaces/S000040/properties/P000086.md
spaces/S000041/properties/P000086.md
spaces/S000042/properties/P000086.md
spaces/S000044/properties/P000086.md
spaces/S000045/properties/P000086.md

Addresses several things in #787

several easy homogeneous results

---

properties/P000132.md

A $G_\delta$ space (P132) is often called "perfect space" in the literature.  So adding this as an alias.

Perfect space as alias for P132

---

spaces/S000139/README.md

S139 alias

---

spaces/S000201/README.md
spaces/S000201/properties/P000016.md
spaces/S000201/properties/P000184.md

Add infinite earring

---

spaces/S000139/README.md
spaces/S000201/README.md

Compare S139 and S201

---

spaces/S000076/properties/P000180.md

Would it be interesting to have a property like "every discrete subspace is countable"?
Some time ago I read about such property being called countable spread.

Sorgenfrey plane is not hereditarily separable.

---

spaces/S000185/properties/P000130.md

Answers https://topology.pi-base.org/spaces?q=Second+countable%2BWeakly+locally+compact%2B%7ELocally+compact

add S185|P130 false

---

properties/P000152.md

Fix P152 typo, closes #805

---

properties/P000152.md

Adding a published reference for topologically countable P152 and an additional reference for the equivalence of the properties listed.

add ref to top count

---

theorems/T000072.md

T72 is strengthened to conclude [P88](https://topology.pi-base.org/properties/P000088) Collectionwise normal from [P40](https://topology.pi-base.org/properties/P000040) Ultraconnected.

Strengthen T72

---

spaces/S000131/README.md
spaces/S000185/README.md
spaces/S000202/README.md
spaces/S000202/properties/P000023.md
spaces/S000202/properties/P000126.md
spaces/S000202/properties/P000181.md
spaces/S000202/properties/P000184.md

Add metric fan

---

spaces/S000201/properties/P000038.md
spaces/S000201/properties/P000043.md

This is a first attempt of responding to #798 . I only used a minimal wording "The proof is similar to S139 is arc-connected/locally arc-connected" (yeah, I was lazy). But I would be happy to add more content later should you think it is appropriate.

Infinite earring is arc-connected and locally arc-connected

---

spaces/S000043/properties/P000022.md
spaces/S000076/properties/P000022.md
spaces/S000101/properties/P000022.md
spaces/S001103/properties/P000022.md

Pseudocompact traits

---

theorems/T000609.md

New T609: Has a generic point + T0 + Alexandrov ==> Has an isolated point

T609: Generic point in T0 Alexandrov space is isolated

---

spaces/S000186/properties/P000051.md

Closes #858 and answers https://topology.pi-base.org/spaces?q=%7ELocally+Hausdorff%2BTotally+disconnected

prove S186|P51

---

theorems/T000611.md

See #878 
(Sorry about missing that typo!)

T611 hotfix

---

spaces/S000170/properties/P000200.md

Added that $S^1$ is not simply connected.
I'm not shure how detailed the proof of this fact should be so I will edit it if it's to detailed or not detailed enough.

The circle is not simply connected

---

properties/P000076.md
theorems/T000177.md
theorems/T000475.md
theorems/T000570.md

Closes #827
Extends work of @danflapjax from that PR to make it ready to merge, assuming others agree.

Proximal game results

---

spaces/S000144/properties/P000126.md
spaces/S000187/properties/P000126.md
spaces/S000188/properties/P000001.md
spaces/S000188/properties/P000126.md

Three finite spaces had the Door property marked as unknown.  Add a trait file for those.

Door trait for some finite spaces

---

properties/P000085.md
properties/P000102.md

Compare with #626 - either we should prune these as is done here, or at the very least add theorems connecting them to other properties.

Remove unused properties

---

spaces/S000020/README.md
spaces/S000033/README.md
spaces/S000034/README.md
spaces/S000035/README.md
spaces/S000036/README.md

Better names and alias cleanup for ordinal spaces, as discussed in latest community meeting.
https://topology.pi-base.org/spaces?q=ordinal%2B%7EFinite

Better names for ordinal spaces

---

spaces/S000164/properties/P000186.md

Answers https://topology.pi-base.org/spaces/S000164/properties/P000186
Addresses #902

Add S164|P186

---

spaces/S000175/properties/P000086.md

What do we think about this proof? 
The connectivity properties of the radial plane don't seem to be explored very much.

Radial plane is Homogeneous

---

properties/P000201.md
properties/P000202.md
properties/P000203.md
spaces/S000007/README.md
spaces/S000008/README.md
spaces/S000009/README.md
spaces/S000188/properties/P000203.md
theorems/T000571.md
theorems/T000572.md
theorems/T000573.md
theorems/T000574.md
theorems/T000575.md
theorems/T000576.md
theorems/T000577.md
theorems/T000578.md

I decided to split up #821 for the sake of my (lack of) time and wanting to get the changes finally shipped.

Almost discrete part 1

---

properties/P000102.md
theorems/T000615.md
theorems/T000616.md

Closes #626.
@danflapjax probably has much more to add, but I wanted to go ahead and get this wired up with the rest of pi-Base, and this feels like the MVP to do so.

add semimetrizable theorems

---

spaces/S000011/properties/P000010.md

S11 is P10

---

properties/P000192.md
spaces/S000044/properties/P000086.md
spaces/S000044/properties/P000192.md
spaces/S000044/properties/P000201.md

Nested interval topology S44 is quasi-sober P192

---

theorems/T000261.md

Oops, I meant open, not closed 😅

Fix typo in T261

---

spaces/S000137/README.md

Makes URL at https://topology.pi-base.org/spaces/S000137 clickable.

Linkify URL

---

spaces/S000188/properties/P000010.md
spaces/S000188/properties/P000049.md

Adding two traits for S188

---

properties/P000029.md

At the very least, there are [several questions](https://math.stackexchange.com/search?q=%22Suslin+property%22) on MathSE using this terminology, and [it gets mention on Wikipedia](https://en.wikipedia.org/wiki/Countable_chain_condition).

Add Suslin property alias to P29

---

spaces/S000144/properties/P000089.md
spaces/S000144/properties/P000204.md

Completing all traits for finite spaces (excluding semimetrizable, which will be completed once symmetrizable is added).

Adding two traits for S144

---

spaces/S000169/README.md
spaces/S000169/properties/P000003.md
spaces/S000169/properties/P000016.md
spaces/S000169/properties/P000086.md
spaces/S000169/properties/P000087.md
spaces/S000169/properties/P000089.md
spaces/S000169/properties/P000123.md
spaces/S000169/properties/P000137.md
spaces/S000169/properties/P000199.md
spaces/S000169/properties/P000200.md

Closes #981.
(An extra comment: I did not expect just asserting the few properties discussed in the issue is enough to imply every possible trait, except the impossible one Cardinality = $\aleph_1$. That was truly a surprise.)

Adding sphere

---

properties/P000088.md
properties/P000145.md
theorems/T000546.md
theorems/T000547.md

Minor clarifications for P88 and P145.
Also trivial tweaks for two theorems.

Minor clarifications for P88 and P145

---

properties/P000040.md
properties/P000207.md
spaces/S000207/README.md
spaces/S000207/properties/P000003.md
spaces/S000207/properties/P000088.md
spaces/S000207/properties/P000207.md
theorems/T000214.md
theorems/T000648.md
theorems/T000649.md
theorems/T000656.md

add strongly collectionwise normal

---

spaces/S000185/properties/P000051.md

Show that S185 is scattered (and thus Baire).

add S185 scattered

---

spaces/S000139/properties/P000038.md
spaces/S000201/properties/P000038.md

I should have removed arc connected from these when I added 'Has a cut point'.

Bouquet + Ear Trait Cleanup

---

spaces/S000168/README.md
spaces/S000168/properties/P000016.md
spaces/S000168/properties/P000086.md
spaces/S000168/properties/P000089.md
spaces/S000168/properties/P000123.md
spaces/S000168/properties/P000200.md
spaces/S000169/properties/P000087.md

Add projective plane, resolve #893

---

spaces/S000154/properties/P000061.md

 Fort space on real numbers is not cozero complemented

---

.github/ISSUE_TEMPLATE/new-trait-suggestion.md

What do we think about this wording? (See discussion at #1055.)

Suggest a PR for traits rather than issue

---

spaces/S000072/README.md

More instructive first line for S72

---

properties/P000099.md

sequential compact/closed characterization of P99 US

---

theorems/T000664.md
theorems/T000674.md

New T674: Almost discrete + T1 => monotonically normal.
This allows to derive that 6 more spaces are monotonically normal.
Also added reference for T664.

Almost discrete T1 spaces are monotonically normal

---

spaces/S000066/README.md
spaces/S000066/properties/P000204.md

Answers https://topology.pi-base.org/spaces/S000066/properties/P000204
Note the change in name for S66.

Double origin plane S66 does not have a cut point P204

---

theorems/T000589.md

Tweak to T589 (indiscrete => simply connected)
as discussed in https://github.com/pi-base/data/pull/1115#issuecomment-2549971601.

Tweak to T589 (indiscrete => simply connected)

---

spaces/S000107/properties/P000041.md
spaces/S000107/properties/P000046.md

After a lot of struggle (and some help), I've finally obtained components of the box product of reals.
Turns out those are the (closed) nowhere dense sets $A = \\{y : x_n = y_n\text{ for all but finitely many }n\\}$.

Box product of reals and is not locally connected

---

spaces/S000016/properties/P000101.md
spaces/S000016/properties/P000142.md
spaces/S000016/properties/P000199.md

Since I don't know any game theory, I've left the properties which were of that nature.
But all the other properties are established here.

Add non-game theoretic traits to cofinite topology on $\mathbb{R}$

---

spaces/S000152/README.md
spaces/S000152/properties/P000039.md
spaces/S000152/properties/P000073.md
spaces/S000152/properties/P000075.md
spaces/S000152/properties/P000090.md
spaces/S000152/properties/P000181.md
spaces/S000152/properties/P000202.md

This is part 2 of #1018, which adds a space that is hyperconnected, ultraconnected, compact, sober, and Alexandrov, but not spectral. This demonstrates that the hereditarily connected condition in [T554](https://topology.pi-base.org/theorems/T000554) cannot be weakened.

Part 2 of #1018: An example of a space that is hyperconnected, ultraconnected, compact, sober, and Alexandrov, but not spectral

---

theorems/T000575.md
theorems/T000681.md

New T681: Ultraparacompact => fully normal.
Also, simplification of T575.

T681: Ultraparacompact spaces are fully normal

---

properties/P000162.md

The main issue was that there was no assumption of being Tychonoff when discussing equivalent definition of realcompactness.
Also, I tried making everything clearer.

Definition of realcompactness

---

spaces/S000142/README.md

Fix description of S142 (Erdos space)

---

theorems/T000684.md
theorems/T000685.md

This also clears trait of S158 (Unit interval $[0, 1]$), and may be good for adding manifolds (e.g., $S^3$, etc.) in future.

Theorems about manifolds

---

spaces/S000110/properties/P000117.md
spaces/S000110/properties/P000206.md

Continuing #1128 and #1129, this is the third PR in a series to complete (as far as I can) the traits of S110, the strong ultrafilter topology. This one added P117 (Has a $\sigma$-locally finite network) and P206 (Strongly Choquet).

Part 3 of completing S110

---

spaces/S000122/README.md

Fix/tweak S122 description

---

spaces/S000188/properties/P000002.md
spaces/S000188/properties/P000036.md
spaces/S000188/properties/P000049.md
spaces/S000188/properties/P000126.md
theorems/T000671.md
theorems/T000672.md

Interestingly, being almost discrete and not semiregular fully characterizes a space up to cardinality, so we can have some very strong theorems involving the two properties.

Two theorems about non-semiregular almost discrete spaces, plus a fixed trait

---

spaces/S000188/properties/P000036.md

Restore trait P36 Connected to S188

---

spaces/S000139/README.md
spaces/S000201/README.md

Follow up to #881.
See in particular https://github.com/pi-base/data/pull/881#issuecomment-2565861965.

Tweaks for S139 S201

---

spaces/S000072/README.md

Closes #1089
In addition to fixing the tuple notation, I simplified notation for the local bases.

Fix S72 description

---

theorems/T000692.md

Resolves #1189 
Theorem T692: P36 + P145 => P18
(connected + strongly paracompact => Lindelof)

Adding theorem on connected strongly paracompact spaces

---

theorems/T000698.md

paracompact + locally compact + connected implies exhaustible by compacts

---

spaces/S000209/README.md
spaces/S000209/properties/P000016.md

Continuing from here https://github.com/pi-base/data/pull/1159#issuecomment-2566032619 
Sorry for the confusion. I didn't realize my commits weren't going through because the PR was already closed, and I didn't notice the error message.

Circle with two origins fresh

---

properties/P000174.md
spaces/S000022/README.md
spaces/S000022/properties/P000172.md
spaces/S000155/README.md
spaces/S000155/properties/P000114.md
spaces/S000155/properties/P000133.md
spaces/S000155/properties/P000147.md
spaces/S000155/properties/P000151.md
spaces/S000155/properties/P000174.md
spaces/S000155/properties/P000203.md
spaces/S000157/README.md
spaces/S000157/properties/P000002.md
spaces/S000157/properties/P000029.md
spaces/S000157/properties/P000059.md
spaces/S000157/properties/P000114.md
spaces/S000157/properties/P000147.md
spaces/S000157/properties/P000151.md
spaces/S000157/properties/P000154.md
spaces/S000157/properties/P000172.md
spaces/S000157/properties/P000174.md
spaces/S000157/properties/P000203.md

Adding S155/S157: Fortissimo spaces of size aleph_1 and aleph_2
as discussed in #1213.
I added Proposition 4 in
https://math.stackexchange.com/questions/4833761/lots-and-radial-properties-for-generalized-fort-fortissimo-spaces
and also https://math.stackexchange.com/a/5030171.
Hopefully someone can check that at the same time.
@StevenClontz The only remaining unknown trait is 2-Markov Menger.  Maybe you would have an idea.

S155/S157: Fortissimo spaces of size aleph_1 and aleph_2

---

properties/P000049.md
properties/P000085.md
theorems/T000695.md

Trivial wording tweak for extremally disconnected

---

theorems/T000400.md

Loosening the assumption of P147 to P87.
Mentioned in #1227

T400 update: connected + basically disconnected => strongly connected

---

spaces/S000149/README.md
spaces/S000149/properties/P000015.md
spaces/S000149/properties/P000019.md
spaces/S000149/properties/P000062.md
spaces/S000149/properties/P000065.md
spaces/S000149/properties/P000089.md
spaces/S000149/properties/P000123.md
spaces/S000149/properties/P000133.md
spaces/S000149/properties/P000199.md
spaces/S000149/properties/P000200.md

New S149: Two-sided long line, as suggested in #1264.

S149: Two-sided long line

---

spaces/S000122/README.md
spaces/S000122/properties/P000004.md
spaces/S000122/properties/P000010.md
spaces/S000122/properties/P000204.md

This would resolve #1034 #1035 and #1037

Gustin's sequence space separation properties and cut points

---

properties/P000049.md

Note that locally dense exists in literature e.g. _Metrizability of certain countable unions_ by Corson and Michael

Extremally disconnected is hereditary with respect to locally dense sets

---

spaces/S000024/properties/P000151.md

This is the last property I'm adding for this space, we can do cleanup after all of them are approved.

Modified Fort space on $\mathbb{R}$ is strategically Rothberger

---

theorems/T000741.md

hereditarily Lindelof Hausdorff spaces are of size at most continuum

---

properties/P000010.md

Some meta-properties for P10 (semiregular).
As given by @yhx-12243 in https://github.com/pi-base/data/pull/1382#issuecomment-3170387153.

Meta-properties for semiregular

---

properties/P000053.md
properties/P000112.md
properties/P000121.md
properties/P000166.md
spaces/S000182/README.md
spaces/S000182/properties/P000056.md
spaces/S000182/properties/P000065.md
spaces/S000182/properties/P000087.md
spaces/S000182/properties/P000166.md

Add a few meta-properties for disjoint unions as suggested in #1385.
Also took the opportunity for some minor tweaks for S180.

Some meta-properties with disjoint unions

---

spaces/S000002/README.md

Added the aliases "The Natural Numbers" and "The Integers" to S2.

Added two aliases for S2

---

theorems/T000778.md

Resolves 7 undetermined cases of hereditary paracompactness

Almost discrete implies hereditarily paracompact

---

spaces/S000199/properties/P000089.md

Left ray topology on ω does not have the Fixed point property

---

spaces/S000159/properties/P000089.md
spaces/S000166/properties/P000089.md
spaces/S000167/properties/P000089.md

Use a powerful fixed point theorem to generate some fixed points

Tarski's fixed point theorem

---

properties/P000168.md
theorems/T000793.md

https://topology.pi-base.org/spaces?q=168+%2B+%3F103 (Discovering when exploring the new space S214)

P168 (Countable sets are discrete) ⇒ P103 (Strongly KC)

---

properties/P000047.md
theorems/T000794.md

See discussion in https://github.com/pi-base/data/pull/1472#issuecomment-3336830427.

Locally orderable totally disconnected regular space is 0-dim

---

spaces/S000016/properties/P000222.md

It seems that to me, unless I greatly misunderstood, S16 (the cofinite topology on R) is P222 (cofinite) by the construction of S16 and the definition of P222. If such is correct, I made a new P222 file with true. I'm also a first timer so I hope all went smoothly.

add P222 to S16
